### ISSUE TITLE
Database location

### ISSUE THREAD

**Issue by mauritce2** [sestaton/Pairfq#9]
Hello, I installed Pairfq over internet and the installation itself is fine and Pairfq work perfectly, but the problem is the database location.  How can I change the location to another physical disk?   My fastq-files are extreme large and for that reason I have all data on another disk.  Pairfq creates the working database on system disk which is not large enough to handle billions reads.

**Comment by sestaton** [comment]
Hi, 

Can you describe why you need to pair billions of reads? This is not a typical scenario and I think you might benefit more from a different approach rather than changing the index location (which can be done). If you have concatenated several lanes of data I would try to work on the subsets instead, that way you can just concatenate the paired subsets separately with no issues.

Thanks.

**Comment by sestaton** [comment]
Hi, 

Could you provide an update on this issue? If not, I might close it because there doesn't seem to be any action that can be taken (without a response).

Thanks.

**Comment by sestaton** [comment]
Please comment if you would like to discuss this issue further.
